typography_spectrum: 0.18741665314882994
color:
  brandStrength: 0.9907011038158089
  lightness: 0.23080532113090158
  saturation: 0.6766814670991153
  rhythmicContrast: 0.3561609780881554
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
layout_spectrum: 0.05958033609203994
author:
  name: COLIN MENZIES
  email: colemenzies@gmail.com
name: Fitness101
